encyclopedia/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("random", views.random, name="random"),
    path("new", views.new, name="new"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("search", views.search, name="search"),
    path("<str:title>", views.entry, name="entry")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
from markdown2 import Markdown
import random as RandomInt
from . import util

markdowner = Markdown()


class EntryForm(forms.Form):
    title = forms.CharField(label="Title", widget=forms.TextInput(attrs={'cols': 60}))
    content = forms.CharField(label="Content", widget=forms.Textarea(attrs={'cols': 120}))


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })


def entry(request, title):
    this_entry = util.get_entry(title)
    if this_entry is not None:
        return render(request, "encyclopedia/entry.html", {
            "entry": markdowner.convert(this_entry),
            "title": title
        })
    else:
        return render(request, "encyclopedia/error.html", {
            "title": title
        })


def random(request):
    entries_list = util.list_entries()
    random_title = entries_list[RandomInt.randint(0, len(entries_list) - 1)]
    return HttpResponseRedirect(reverse("entry", kwargs={'title': random_title}))


def new(request):
    if request.method == "POST":
        form = EntryForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            content = form.cleaned_data["content"]
            if title not in util.list_entries():
                util.save_entry(title, content)
                return HttpResponseRedirect(reverse("entry", kwargs={'title': title}))
            else:
                context = {
                    'form': EntryForm(),
                    'message': f"Entry with title {title} already exists."
                }
            return render(request, "encyclopedia/new.html", context)
    else:
        context = {
            'form': EntryForm()
        }
        return render(request, "encyclopedia/new.html", context)


def edit(request, title):
    if request.method == "POST":
        content = request.POST['content']
        util.save_entry(title, content)
        return HttpResponseRedirect(reverse("entry", kwargs={'title': title}))
    else:
        context = {
            "title": title,
            "content": util.get_entry(title)
        }
        return render(request, "encyclopedia/edit.html", context)


def search(request):
    all_entries = util.list_entries()
    title = request.POST["title"]
    if title in all_entries:
        return HttpResponseRedirect(reverse('entry', kwargs={'title': title}))
    else:
        matching_entries = []
        for entry in all_entries:
            if title.lower() in entry.lower():
                matching_entries.append(entry)
        return render(request, "encyclopedia/search.html", {
            "entries": matching_entries,
            "query": title,
            "count": len(matching_entries)
        })

encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }} | Edit
{% endblock %}

{% block body %}
    {{message}}
    <form action="{% url 'edit' title %}" method="POST">
    {% csrf_token %}
    <table>
    <tr>
        <th><label for="title">Title:</label></th>
        <td><input type="text" name="title" cols="60" required disabled value="{{title}}" id="title"></td>
    </tr>
    <tr>
        <th><label for="content">Content:</label></th>
        <td>
            <textarea name="content" cols="120" rows="10" required id="id_content">{{content}}</textarea>
        </td>
    </tr>
    </table>
    <input type="submit" value="Edit">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block nav %}
<div style=" padding:3px;margin-top:360px;">
    <a href="{% url 'edit' title%}">Edit this page</a>
</div>
{% endblock %}

{% block body %}
    {{ entry | safe }}
{% endblock %}

encyclopedia/templates/encyclopedia/error.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}
    <h1>{{ title }}</h1>
    <h3> There is no entry in this encyclopedia with the title {{title}}.</h3>
    <br/><br/><br/>
    <button>Create this entry with this title.</button>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
        <li><a href="{% url 'entry' entry %}">{{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2><a href="{% url 'index' %}">Wiki</a></h2>
                <form action="{% url 'search' %}" method="POST">
                    {% csrf_token %}
                    <input class="search" type="text" name="title" placeholder="Search Encyclopedia">
                    <input type="submit" value="Search">
                </form>
                <div>
                    <a href="{% url 'index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'new' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'random' %}">Random Page</a>
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    New Entry
{% endblock %}

{% block body %}
    {{message}}
    <form action="{% url 'new' %}" method="POST">
    {% csrf_token %}
    <table>
    {{ form }}
    </table>
    <input type="submit" value="Add">
    </form>

{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Search '{{query}}'
{% endblock %}

{% block body %}
    <div class="row">
    <div class="col-6">
    <h3>Matching Pages ({{ count }})</h3>
    </div>
    <div class="col-6">
    <h3>Query : '{{query}}'</h3>
    </div>
    </div>
    <hr>
    <ul>
        {% for entry in entries %}
        <li><a href="{% url 'entry' entry %}">{{ entry }}</a></li>
        {% empty %}
        No matching entry found...
        {% endfor %}
    </ul>

{% endblock %}